### ISSUE TITLE
Métricas de rendimiento

### ISSUE THREAD

**Issue by siraglez** [Roberquilez/UmbrellaCorporation#11]
crear una clase dedicada a las métricas.
implementar un sistema que calcule el tiempo de respuesta medio y la tasa de procesamiento de datos por segundo.
(los criterios de éxito pueden ser parte del monitoreo del sistema, agregando métodos de verificación a la clase principal).

**Comment by Oyupa** [comment]
Se muestran por consola los hilos. Es suficiente?
