### ISSUE TITLE
Elementos visuales

### ISSUE THREAD

**Issue by siraglez** [Roberquilez/UmbrellaCorporation#12]
(essto ya lo tenemos empezado, pero ns si lo hemos terminado asi q lo añado también por si acaso)
realizar una tabla de eventos procesados por tipo de dato y un gráfico de rendimiento del sistema en tiempo real.
el diagrama de arquitectura del sistema lo podemos hacen con un PlantUML al final cuando ya tengamos todo el programa terminado

**Comment by Oyupa** [comment]
Los elementos visuales son los gráficos del csv? Están oprativos desde el commit (https://github.com/Roberquilez/UmbrellaCorporation/commit/59a6bbf1cdf30a94bc259378f02149c559dca9a4)
