### ISSUE TITLE
Monitorización y Logs

### ISSUE THREAD

**Issue by siraglez** [Roberquilez/UmbrellaCorporation#9]
configurar el registro para monitorizar el sistema

**Comment by Roberquilez** [comment]
Monitorización del Sistema:
Clase MonitoringTool: Utiliza JMX (Java Management Extensions) para obtener información sobre los hilos en ejecución. Imprime el número de hilos y sus nombres.
Logging:
Configuración de logback.xml: Define cómo se registrarán los mensajes de log, incluyendo el formato y el destino (consola).
Clase DataProcessor: Implementa el logging para registrar eventos importantes y errores durante el procesamiento de datos.
